print("Result.csv\n",
"\n",
"\n",
"    \n",
"result_schema=['Id','Status','BoardId','BatchId','WorkOrderId','RoutingStageId','RoutingStageName','Operator','Deviation','InspectionDate','LastModifiedDate','ReInspectionNeeded','PreviouslySannedBoards','RoutingStatus','CavityID','SubWorkCenter','StationCode','StationName','TrayId','AssetSubNodeId','CollectionId','Company','Division']\n",
"result_1=[]\n",
"for col in df[1].columns:\n",
"    result_1.append(col)\n",
"print(result_1)\n",
"\n",
"\n",
"dicts = {}\n",
"keys = result_1\n",
"values = result_schema\n",
"j=0\n",
"for i in keys:\n",
"        dicts[i] = result_schema[j]\n",
"        j=j+1\n",
"print(dicts)\n",
"\n",
"df[1].rename(columns=dicts,\n",
"          inplace=True)\n",
"\n",
"\n",
"df[1].loc[-1] = result_1  # adding a row\n",
"df[1].index = df[1].index + 1  # shifting index\n",
"df[1].sort_index(inplace=True) \n",
" \n",
"# call rename () method\n",
"\n",
"df[1]\n",
"df[1].to_csv('../LAKEHOUSE_SILVER_LAYER/result.csv',index=False)\n")